after_training: ''
agent: deprl.custom_agents.dep_factory(3, deprl.custom_mpo_torch.TunedMPO())(replay=deprl.replays.buffers.Buffer(return_steps=3,
  batch_size=256, steps_between_batches=1000, batch_iterations=30, steps_before_batches=2e5))
before_training: ''
checkpoint: last
env_args: {}
environment: deprl.environments.Gym('myoAmpWalk-v0', reset_type='random', scaled_actions=False)
environment_name: deprl_baseline
full_save: false
header: import deprl, gym, myosuite
mpo_args:
  hidden_size: 1024
  lr_actor: 3.0e-05
  lr_critic: 7.0e-05
  lr_dual: 0.00213
name: myo_amputation_1
parallel: 7
path: baselines_DEPRL
preid: 0
seed: 0
sequential: 7
test_environment: null
trainer: deprl.custom_trainer.Trainer(steps=int(2e8), epoch_steps=int(2e5), save_steps=int(1e5))
